### ISSUE TITLE
Fail to run 'run_experiment'

### ISSUE THREAD

**Issue by tyq1024** [apexrl/COIL#1]
“bc_exp_script.py", line 26, in experiment
    print(variant['expert_name'])
KeyError: 'expert_name'

**Comment by Ericonaldo** [comment]
Sorry for the missing yaml file. We will sort up and provide a set of parameter files that reproduces our exps this week. I will remind you in this issue once we done it.

**Comment by FineArtz** [comment]
Thanks for your feedback! We have updated our demonstration experiment settings. Sorry for the mistake again.

**Comment by Ericonaldo** [comment]
@tyq1024 Please see https://github.com/apexrl/COIL/tree/master/specs for supplemented exp yaml files.

**Comment by tyq1024** [comment]
Thanks!

**Comment by KeysaYoung** [comment]
1. running demo_spec.yaml
 
File "run_scripts/coil_script.py", line 167, in <module>
    experiment(exp_specs, snapshot=snapshot, extra_data=extra_data)
  File "run_scripts/coil_script.py", line 57, in experiment
    env_specs['eval_env_seed'], variant['coil_params']['discount'],
KeyError: 'discount'

 2. running hc_md.yaml
 
  File "run_experiment.py", line 36, in <module>
    for variant in vg_fn():
  File "/COIL/rlkit/launchers/launcher_util.py", line 457, in vg_fn
    dict_to_yield = add_variable_to_constant_specs(constants, flat_variables)
  File "/COIL/rlkit/launchers/launcher_util.py", line 428, in add_variable_to_constant_specs
    cur_sub_dict = cur_sub_dict[sub_key]
KeyError: 'coil_params'
